# Generated by Django 5.2.7 on 2025-12-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcodedata',
            name='tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='retake_app.tree'),
            preserve_default=False,
        ),
    ]
