# Generated by Django 5.2.7 on 2025-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_app', '0002_zipcodedata_tree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='ZipCodeData',
        ),
    ]
