# Generated by Django 5.2.7 on 2025-12-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_app', '0003_alter_tree_zip_code_delete_zipcodedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='zip_code_trees',
            field=models.ManyToManyField(blank=True, related_name='related_trees', to='retake_app.tree'),
        ),
    ]
