# Generated by Django 5.2.7 on 2025-12-12 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_app', '0004_tree_zip_code_trees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='zip_code_trees',
        ),
        migrations.AddField(
            model_name='tree',
            name='zip_code_trees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_code', to='retake_app.user'),
        ),
    ]
