# Generated by Django 5.2.7 on 2025-12-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retake_app', '0005_remove_tree_zip_code_trees_tree_zip_code_trees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='mapped_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='retake_app.user'),
        ),
    ]
